blog/urls.py
from django.urls import path
from .views import BlogListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='delete')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self) -> str:
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, 'blog_list.html', context)

class PostCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm()
        context = {
            'form': form
        }
        return render(request, 'post_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
        context = {

        }
        return render(request, 'post_create.html', context)
    
class PostDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post': post
        }
        return render(request, 'post_detail.html', context)
    
class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'post_update.html'

    def get_success_url(self) -> str:
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})
    
class PostDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

templates/base.html
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% tailwind_css %}
    
    <title>Document</title>
</head>
<body>
    
    <!-- Esto nos permite enviar información de manera dinámica a las otras vistas -->
    {% block content %}{% endblock content %}

</body>
</html>

templates/blog_list.html
Posts
<br><br><br>
{% for post in posts %}
    <a href="{% url 'blog:detail' post.id%}">{{post.title}}</a>
    (
        <a href="{% url 'blog:update' post.id%}">Update</a> -
        <a href="{% url 'blog:delete' post.id%}">Delete</a>
    )
    <br>
{% endfor %}
<a href="{% url 'blog:create' %}">Create post</a>

templates/index.html
{% extends 'base.html' %}
{% block content %}
Visit my <a class="text-blue-500" href="{% url 'blog:home' %}">BLOG</a>
{% endblock content %}

templates/post_create.html
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <br>
    <button type='submit'>Submit</button>
</form>

templates/post_delete.html
Are you sure?
<form method='POST'>
    {% csrf_token %}
    {{form}}
    <button type='submit'>Delete</button>
</form>

templates/post_detail.html
{{post.title}}
<br>
{{post.content}}

templates/post_update.html
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <br>
    <button type='submit'>Update</button>
</form>